### PR TITLE
Visa historical data

### PR DESCRIPTION
**Pull request by 1mshy**
I added an example with a large dataset of historical pricing data on the ticker symbol V (Visa).

### CODE REVIEW

**Review by 0100101001010000 — APPROVED** [review]
I need to find a better way to store large amount of data in the examples, but as far as this PR goes ✅

**Comment by 1mshy** [comment]
I can store it in a json file, but would need to add dependencies

**Comment by 0100101001010000** [comment]
No worries, I've got the other test file to clean up to. I'll do a refactor
down the line.

Just let me know when you want me to merge, and I'll release it.

Appreciate the PR BTW!

**Comment by 1mshy** [comment]
All good to merge, np

**Comment by 1mshy** [comment]
I am creating a desktop app to look through stocks and want to introduce some technical analysis, will probably use this library down the line. If you ever need data I know very strong and free apis from yahoo.

**Comment by 0100101001010000** [comment]
> If you ever need data I know very strong and free apis from yahoo
Sounds good, if I ever do I'll reach out

**Comment by 0100101001010000** [comment]
> I am creating a desktop app to look through stocks and want to introduce some technical analysis

Sounds fun, I'll keep an eye on your repos

**Pull request merged**
